// Hướng dẫn kỹ thuật từng bài trong chương trình 6 ngày.
// rx: số set × rep gợi ý cho giai đoạn giảm mỡ (giữ tạ nặng ở bài compound để giữ cơ).
// video: từ khoá tìm video hướng dẫn (mở YouTube ở tab mới).

const G = (o) => o;

export const GUIDES = {
  // ---------- D1 Ngực ----------
  'Incline Barbell/Smith Bench Press': G({
    muscles: 'Ngực trên, vai trước, tay sau',
    rx: '4 × 6–8 · nghỉ 90–120s',
    setup: ['Ghế dốc 30–45° (nấc 3–4).', 'Nằm sao cho thanh đòn rơi ngang xương đòn trên.', 'Ép hai bả vai ra sau và xuống, ưỡn nhẹ lưng, hai chân bám chắc sàn.', 'Nắm rộng hơn vai một chút, cổ tay thẳng.'],
    steps: ['Gỡ tạ, giữ tay thẳng trên ngực trên.', 'Hít vào, hạ thanh đòn có kiểm soát (2–3 giây) chạm nhẹ ngực trên.', 'Khuỷu tay hợp với thân khoảng 45–60°, không bè ngang 90°.', 'Thở ra, đẩy thẳng lên đến gần duỗi hết tay.'],
    cues: ['Bả vai luôn khoá, không nhô vai lên khi đẩy.', 'Cẳng tay vuông góc sàn ở điểm thấp nhất.'],
    mistakes: ['Ghế quá dốc (>45°) thành bài vai.', 'Nảy tạ khỏi ngực.', 'Mông nhấc khỏi ghế.'],
    safety: 'Tập nặng với barbell nên có người trợ lực; Smith machine thì cài chốt an toàn.',
    video: 'incline barbell bench press form',
  }),
  'Incline Dumbbell Press': G({
    muscles: 'Ngực trên, vai trước, tay sau',
    rx: '3 × 8–10 · nghỉ 90s',
    setup: ['Ghế dốc 30°.', 'Đặt tạ lên đùi, ngả lưng và dùng gối đẩy tạ lên vị trí ngực.', 'Bả vai ép ra sau, lòng bàn tay hướng về chân hoặc hơi xoay vào trong.'],
    steps: ['Đẩy tạ lên trên ngực trên, hai tạ gần chạm nhau.', 'Hạ chậm xuống ngang ngực, khuỷu tay hơi khép (~45°), cảm nhận ngực căng.', 'Đẩy lên theo đường cong nhẹ vào giữa.'],
    cues: ['Biên độ sâu hơn barbell: hạ đến khi ngực căng hết.', 'Giữ tạ ổn định, không để tạ đổ ra ngoài.'],
    mistakes: ['Đập hai tạ vào nhau ở trên.', 'Hạ quá nông.'],
    safety: 'Kết thúc set: đưa tạ về ngực, co gối, ngồi dậy cùng tạ thay vì thả tạ sang hai bên.',
    video: 'incline dumbbell press form',
  }),
  'Pec Deck Fly (hoặc Cable Crossover)': G({
    muscles: 'Ngực (cô lập)',
    rx: '3 × 12–15 · nghỉ 60s',
    setup: ['Chỉnh ghế để tay cầm ngang ngực giữa.', 'Lưng áp sát đệm, ngực ưỡn, vai hạ.', 'Cable crossover: ròng rọc cao vừa, bước lên một bước, hơi nghiêng người.'],
    steps: ['Khuỷu tay hơi cong cố định, khép tay ôm vào trước ngực.', 'Siết ngực 1 giây ở điểm khép.', 'Mở tay chậm về sau đến khi ngực căng, không vượt quá vai.'],
    cues: ['Tưởng tượng ôm một thân cây lớn.', 'Chuyển động ở khớp vai, không gập duỗi khuỷu.'],
    mistakes: ['Dùng quán tính kéo tạ.', 'Mở tay quá sâu ra sau làm đau vai trước.'],
    safety: '',
    video: 'pec deck fly form',
  }),
  'Dips (Chống xà kép)': G({
    muscles: 'Ngực dưới, tay sau, vai trước',
    rx: '3 × tối đa (8–12) · nghỉ 90s',
    setup: ['Chống tay trên xà kép, tay thẳng, vai hạ xuống khỏi tai.', 'Nghiêng thân ra trước ~20–30° để dồn vào ngực.'],
    steps: ['Co khuỷu, hạ người đến khi cánh tay trên song song sàn.', 'Đẩy lên đến gần thẳng tay.'],
    cues: ['Khuỷu hơi mở ra ngoài khi muốn tập ngực, khép sát khi muốn tập tay sau.', 'Không để nhô vai lên ở điểm thấp.'],
    mistakes: ['Hạ quá sâu khi vai còn yếu.', 'Đung đưa chân lấy đà.'],
    safety: 'Đau vai trước thì giảm biên độ hoặc dùng máy dips có trợ lực. Để trống ô kg = bodyweight; đeo thêm tạ thì nhập số kg đeo.',
    video: 'chest dips form',
  }),

  // ---------- D2 Lưng ----------
  'Pull-ups (ROM tối đa, nhả hết vai)': G({
    muscles: 'Xô (lat), cơ lưng giữa, tay trước',
    rx: '4 × tối đa (6–10) · nghỉ 120s',
    setup: ['Nắm xà sấp tay, rộng hơn vai một chút.', 'Treo người, tay duỗi hết, vai nhả lên (dead hang).'],
    steps: ['Hạ vai xuống và ép bả vai trước khi co tay.', 'Kéo khuỷu xuống về phía hông, đưa ngực lên gần xà, cằm qua xà.', 'Hạ chậm 2–3 giây về treo thẳng tay, nhả hết vai.'],
    cues: ['Nghĩ "kéo khuỷu xuống túi quần", không nghĩ kéo bằng tay.', 'Siết bụng, chân hơi chéo trước để không đung đưa.'],
    mistakes: ['Nửa biên độ, không duỗi hết tay.', 'Giật người, đá chân (kipping).'],
    safety: 'Chưa kéo được thì dùng máy hỗ trợ hoặc dây kháng lực; để trống ô kg = bodyweight.',
    video: 'pull up proper form full range',
  }),
  'Lat Pulldown': G({
    muscles: 'Xô (lat), lưng giữa',
    rx: '3 × 10–12 · nghỉ 90s',
    setup: ['Chèn đùi dưới đệm, nắm thanh rộng hơn vai.', 'Ngả thân ra sau ~10–15°, ngực ưỡn.'],
    steps: ['Hạ vai xuống, kéo thanh về ngực trên.', 'Siết bả vai 1 giây.', 'Thả lên chậm đến khi tay duỗi hết và xô căng.'],
    cues: ['Khuỷu đi xuống và ra sau.', 'Thanh chạm ngực trên, không kéo ra sau gáy.'],
    mistakes: ['Ngả người quá nhiều thành bài chèo.', 'Dùng tay sau kéo thay vì lưng.'],
    safety: '',
    video: 'lat pulldown form',
  }),
  'Bent-over Barbell Row': G({
    muscles: 'Lưng giữa, xô, cơ lưng dưới (giữ thăng bằng)',
    rx: '4 × 8–10 · nghỉ 90–120s',
    setup: ['Đứng rộng bằng hông, nắm thanh rộng hơn vai một chút.', 'Gập hông, lưng thẳng tự nhiên, thân nghiêng 30–45° so với sàn, gối hơi chùng.'],
    steps: ['Kéo thanh về rốn/bụng dưới, khuỷu đi sát thân.', 'Siết bả vai 1 giây.', 'Hạ chậm đến khi tay duỗi.'],
    cues: ['Giữ lưng phẳng suốt set, nhìn xuống sàn trước mặt.', 'Thân không bật lên xuống theo từng rep.'],
    mistakes: ['Cong lưng dưới.', 'Giật người lấy đà.'],
    safety: 'Đau lưng dưới thì chuyển sang chest-supported row hoặc cable row.',
    video: 'barbell bent over row form',
  }),
  'One-arm Dumbbell Row': G({
    muscles: 'Xô, lưng giữa',
    rx: '3 × 10–12 mỗi bên · nghỉ 60s',
    setup: ['Một tay và một gối chống lên ghế phẳng, chân kia đứng vững.', 'Lưng song song sàn, tay cầm tạ duỗi thẳng.'],
    steps: ['Kéo tạ theo đường cong về phía hông.', 'Siết lưng ở đỉnh.', 'Hạ chậm, để xô giãn hết.'],
    cues: ['Khuỷu đi về phía túi quần sau.', 'Không xoay thân mở ngực.'],
    mistakes: ['Kéo tạ thẳng lên vai.', 'Xoay người dùng đà.'],
    safety: '',
    video: 'one arm dumbbell row form',
  }),

  // ---------- D3 Chân & Mông ----------
  'Wide-stance Barbell Squat': G({
    muscles: 'Mông, đùi trước, đùi trong',
    rx: '4 × 6–8 · nghỉ 120–150s',
    setup: ['Thanh đặt trên cơ thang (không đặt lên cổ).', 'Hai chân rộng hơn vai 1,5 lần, mũi chân xoay ra 30–45°.', 'Hít sâu, gồng bụng.'],
    steps: ['Đẩy hông ra sau và ngồi xuống, gối đi theo hướng mũi chân.', 'Hạ đến khi đùi song song sàn hoặc sâu hơn nếu lưng vẫn thẳng.', 'Đạp mạnh cả bàn chân, đẩy hông lên, siết mông ở trên.'],
    cues: ['Gối mở ra ngoài, không sụp vào trong.', 'Ngực ưỡn, lưng thẳng.'],
    mistakes: ['Nhón gót.', 'Gối khép vào trong khi đứng lên.', 'Cong lưng dưới ở điểm thấp.'],
    safety: 'Tập trong khung squat, cài thanh chắn an toàn ngang dưới điểm thấp nhất.',
    video: 'wide stance sumo squat barbell form',
  }),
  'Bulgarian Split Squat (với tạ đơn)': G({
    muscles: 'Mông, đùi trước (từng chân)',
    rx: '3 × 8–10 mỗi chân · nghỉ 90s',
    setup: ['Mu bàn chân sau đặt lên ghế cao ngang gối.', 'Chân trước bước xa khoảng 2 bàn chân, cầm tạ đơn hai tay.'],
    steps: ['Hạ thẳng xuống đến khi gối sau gần chạm sàn.', 'Đạp gót chân trước để đứng lên.'],
    cues: ['Nghiêng thân ra trước nhẹ để dồn vào mông.', 'Gối trước theo hướng mũi chân.'],
    mistakes: ['Đứng quá gần ghế làm gối đẩy xa ra trước.', 'Đạp bằng chân sau.'],
    safety: 'Làm quen trước bằng bodyweight để giữ thăng bằng.',
    video: 'bulgarian split squat glute focus form',
  }),
  'Lying / Seated Leg Curl': G({
    muscles: 'Đùi sau (cô lập)',
    rx: '3 × 10–12 · nghỉ 60s',
    setup: ['Chỉnh máy: khớp gối thẳng hàng trục xoay, đệm tì ngay trên gót.', 'Nằm sấp (hoặc ngồi) hông áp sát đệm.'],
    steps: ['Co gối kéo đệm về phía mông.', 'Siết đùi sau 1 giây.', 'Duỗi chậm 2–3 giây.'],
    cues: ['Hông không nhấc khỏi đệm.', 'Mũi chân hướng về ống quyển.'],
    mistakes: ['Thả tạ rơi tự do.', 'Nhấc hông lấy đà.'],
    safety: '',
    video: 'lying leg curl form',
  }),
  'Romanian Deadlift (RDL)': G({
    muscles: 'Đùi sau, mông, cơ dựng lưng',
    rx: '3 × 8–10 · nghỉ 120s',
    setup: ['Đứng rộng bằng hông, cầm thanh ở tư thế đứng thẳng.', 'Gối hơi chùng và giữ nguyên góc đó suốt bài.'],
    steps: ['Đẩy hông ra sau, thanh trượt sát đùi xuống.', 'Hạ đến khi đùi sau căng hết (thường ngang giữa ống quyển).', 'Đẩy hông ra trước để đứng thẳng, siết mông.'],
    cues: ['Thanh luôn sát chân.', 'Lưng thẳng, cổ trung tính.'],
    mistakes: ['Hạ thấp bằng cách cong lưng.', 'Co gối thành squat.'],
    safety: 'Dừng ngay nếu đau lưng dưới; giảm tạ và giảm biên độ.',
    video: 'romanian deadlift form',
  }),

  // ---------- D4 Tay ----------
  'EZ-bar Bicep Curl': G({
    muscles: 'Tay trước',
    rx: '3 × 8–12 · nghỉ 60–90s',
    setup: ['Đứng thẳng, cầm EZ-bar ở chỗ cong, rộng bằng vai.', 'Khuỷu áp sát hai bên thân.'],
    steps: ['Cuộn thanh lên đến ngang ngực, siết tay trước.', 'Hạ chậm 2–3 giây đến gần duỗi hết.'],
    cues: ['Khuỷu đứng yên, chỉ cẳng tay chuyển động.', 'Không ngả người ra sau.'],
    mistakes: ['Đung đưa thân.', 'Đưa khuỷu ra trước ở đỉnh.'],
    safety: '',
    video: 'ez bar curl form',
  }),
  'Incline Dumbbell Curl': G({
    muscles: 'Tay trước (đầu dài)',
    rx: '3 × 10–12 · nghỉ 60s',
    setup: ['Ghế dốc 45–60°, ngả lưng, tay buông thẳng sau thân.'],
    steps: ['Cuộn tạ lên, xoay ngửa lòng bàn tay.', 'Hạ chậm đến khi tay duỗi hết, cảm nhận căng ở vai trước.'],
    cues: ['Cánh tay trên vuông góc sàn, không đưa ra trước.'],
    mistakes: ['Dùng tạ quá nặng làm vai nhô lên.'],
    safety: '',
    video: 'incline dumbbell curl form',
  }),
  'Cable Tricep Pushdown': G({
    muscles: 'Tay sau',
    rx: '3 × 10–12 · nghỉ 60s',
    setup: ['Ròng rọc cao, tay cầm thanh thẳng hoặc dây.', 'Đứng gần máy, hơi nghiêng thân, khuỷu khép sát sườn.'],
    steps: ['Đẩy xuống đến duỗi thẳng tay, siết tay sau.', 'Thả lên chậm đến khi cẳng tay song song sàn.'],
    cues: ['Khuỷu cố định như bản lề.', 'Dùng dây thì tách hai đầu dây ra ở điểm cuối.'],
    mistakes: ['Khuỷu trôi ra trước.', 'Đè cả thân lên để đẩy.'],
    safety: '',
    video: 'tricep pushdown form',
  }),
  'Overhead Cable Extension': G({
    muscles: 'Tay sau (đầu dài)',
    rx: '3 × 10–12 · nghỉ 60s',
    setup: ['Ròng rọc thấp hoặc ngang, quay lưng vào máy, cầm dây sau đầu.', 'Bước một chân lên, gồng bụng.'],
    steps: ['Duỗi tay về phía trước–trên đến thẳng.', 'Hạ chậm sau đầu đến khi tay sau căng hết.'],
    cues: ['Khuỷu hướng ra trước, không bè rộng.'],
    mistakes: ['Ưỡn lưng quá mức.', 'Biên độ ngắn.'],
    safety: '',
    video: 'overhead cable tricep extension form',
  }),
  'Reverse Grip Barbell Curl (phát triển cẳng tay)': G({
    muscles: 'Cẳng tay, cơ cánh tay (brachialis)',
    rx: '3 × 12–15 · nghỉ 60s',
    setup: ['Nắm thanh sấp tay (lòng bàn tay úp), rộng bằng vai.'],
    steps: ['Cuộn thanh lên, giữ cổ tay thẳng.', 'Hạ chậm.'],
    cues: ['Tạ nhẹ hơn curl thường khoảng 30–40%.', 'Khuỷu sát thân.'],
    mistakes: ['Cổ tay gập xuống khi mỏi.'],
    safety: '',
    video: 'reverse grip barbell curl form',
  }),

  // ---------- D5 Vai ----------
  'Dumbbell Side Lateral Raise': G({
    muscles: 'Vai giữa',
    rx: '4 × 12–15 · nghỉ 60s',
    setup: ['Đứng thẳng, hơi nghiêng thân ra trước, tạ hai bên hông.', 'Khuỷu hơi cong.'],
    steps: ['Nâng tạ sang ngang đến ngang vai.', 'Dừng 1 giây, hạ chậm 2–3 giây.'],
    cues: ['Dẫn bằng khuỷu, không phải bàn tay.', 'Hơi nghiêng ngón út lên như rót nước.'],
    mistakes: ['Nhún vai (cơ thang làm việc).', 'Vung tạ lấy đà.'],
    safety: 'Tạ nhẹ, kiểm soát tốt hiệu quả hơn tạ nặng vung.',
    video: 'dumbbell lateral raise form',
  }),
  'Cable Lateral Raise': G({
    muscles: 'Vai giữa',
    rx: '3 × 12–15 mỗi bên · nghỉ 60s',
    setup: ['Ròng rọc thấp nhất, đứng nghiêng, tay xa máy cầm tay cầm ngang trước bụng.'],
    steps: ['Nâng tay sang ngang đến ngang vai.', 'Hạ chậm, giữ căng cáp ở dưới.'],
    cues: ['Cáp giữ lực suốt biên độ, đừng thả chùng.'],
    mistakes: ['Nghiêng người kéo bằng thân.'],
    safety: '',
    video: 'cable lateral raise form',
  }),
  'Face Pull (hoặc Reverse Pec Deck Fly)': G({
    muscles: 'Vai sau, cơ chóp xoay, lưng trên',
    rx: '3 × 12–15 · nghỉ 60s',
    setup: ['Ròng rọc ngang mặt, dùng dây thừng, nắm hai đầu dây.', 'Lùi lại cho cáp căng.'],
    steps: ['Kéo dây về phía trán, tách hai tay ra hai bên tai.', 'Xoay ngoài vai ở cuối (nắm tay hướng lên trần).', 'Thả chậm.'],
    cues: ['Khuỷu cao ngang vai.', 'Siết bả vai.'],
    mistakes: ['Kéo về cổ, khuỷu thấp thành bài chèo.'],
    safety: 'Bài tốt để giữ khớp vai khoẻ cho các bài đẩy.',
    video: 'face pull form',
  }),
  'Dumbbell Shoulder Press': G({
    muscles: 'Vai trước, vai giữa, tay sau',
    rx: '3 × 8–10 · nghỉ 90s',
    setup: ['Ghế dựng gần thẳng (75–90°).', 'Tạ ngang tai, khuỷu hơi ra trước thân.'],
    steps: ['Đẩy tạ lên trên đầu đến gần thẳng tay.', 'Hạ chậm về ngang tai.'],
    cues: ['Lưng áp ghế, không ưỡn quá mức.', 'Siết bụng.'],
    mistakes: ['Hạ quá nông.', 'Ưỡn lưng đẩy như đẩy ngực dốc.'],
    safety: '',
    video: 'seated dumbbell shoulder press form',
  }),

  // ---------- D6 Bụng ----------
  'Decline Weighted Crunch': G({
    muscles: 'Cơ bụng thẳng',
    rx: '3 × 12–15 · nghỉ 60s',
    setup: ['Ghế dốc xuống, móc chân chắc.', 'Ôm đĩa tạ trước ngực.'],
    steps: ['Cuộn thân lên: cằm hướng ngực, cuộn từng đốt sống.', 'Siết bụng ở đỉnh 1 giây.', 'Hạ chậm, không thả rơi.'],
    cues: ['Cuộn chứ không gập hông.', 'Thở ra khi cuộn lên.'],
    mistakes: ['Kéo cổ.', 'Dùng đà bật lên.'],
    safety: '',
    video: 'decline weighted crunch form',
  }),
  'Hanging Leg Raise': G({
    muscles: 'Bụng dưới, cơ gập hông',
    rx: '3 × 10–15 · nghỉ 60s',
    setup: ['Treo trên xà, vai hơi hạ, không đung đưa.'],
    steps: ['Nâng chân (hoặc gối) lên, cuộn xương chậu về phía ngực.', 'Hạ chậm có kiểm soát.'],
    cues: ['Nghĩ "cuộn mông lên", không chỉ nâng chân.', 'Chưa làm được chân thẳng thì co gối.'],
    mistakes: ['Đung đưa người.', 'Chỉ nâng chân đến ngang hông.'],
    safety: 'Để trống ô kg = bodyweight.',
    video: 'hanging leg raise form',
  }),
  'Ab Roller (Con lăn tập bụng)': G({
    muscles: 'Toàn bộ cơ bụng, cơ lõi',
    rx: '3 × 8–12 · nghỉ 60s',
    setup: ['Quỳ trên thảm, hai tay nắm con lăn dưới vai.'],
    steps: ['Gồng bụng, đẩy con lăn ra xa đến khi thân gần song song sàn (vừa sức).', 'Dùng bụng kéo về vị trí ban đầu.'],
    cues: ['Lưng hơi tròn (posterior tilt), không võng lưng.', 'Biên độ tăng dần theo tuần.'],
    mistakes: ['Võng lưng dưới.', 'Lăn quá xa khi chưa đủ khoẻ.'],
    safety: 'Đau lưng dưới thì giảm biên độ ngay.',
    video: 'ab wheel rollout form',
  }),
  'Dumbbell Side Bend': G({
    muscles: 'Cơ liên sườn (bụng chéo)',
    rx: '3 × 12–15 mỗi bên · nghỉ 45s',
    setup: ['Đứng thẳng, một tay cầm tạ đơn, tay kia đặt lên hông.'],
    steps: ['Nghiêng thân về phía có tạ.', 'Dùng sườn bên kia kéo thân về thẳng (và hơi quá).'],
    cues: ['Chỉ nghiêng sang ngang, không gập ra trước.', 'Chuyển động chậm.'],
    mistakes: ['Cầm tạ hai tay cùng lúc (hai bên triệt tiêu nhau).'],
    safety: '',
    video: 'dumbbell side bend form',
  }),

  // ---------- Bài bổ sung cho các chương trình 3–7 buổi ----------
  'Barbell Back Squat': G({
    muscles: 'Đùi trước, mông, đùi sau',
    rx: '4 × 6–8 · nghỉ 120–150s',
    setup: ['Thanh đặt trên cơ thang, hai tay nắm chắc, khuỷu hướng xuống.', 'Chân rộng bằng hoặc hơn vai một chút, mũi chân xoay ra 15–30°.', 'Hít sâu, gồng bụng trước mỗi rep.'],
    steps: ['Đồng thời gập hông và gối, ngồi thẳng xuống giữa hai chân.', 'Hạ đến khi đùi song song sàn hoặc thấp hơn nếu lưng vẫn thẳng.', 'Đạp cả bàn chân, đứng lên, thở ra ở trên.'],
    cues: ['Gối đi theo hướng mũi chân.', 'Trọng tâm ở giữa bàn chân, không nhón gót.'],
    mistakes: ['Gối sụp vào trong.', 'Ngực đổ ra trước, hông bật lên trước vai.'],
    safety: 'Tập trong khung squat, cài thanh chắn an toàn.',
    video: 'barbell back squat form',
  }),
  'Barbell Bench Press': G({
    muscles: 'Ngực, vai trước, tay sau',
    rx: '4 × 6–8 · nghỉ 120s',
    setup: ['Mắt nằm ngay dưới thanh.', 'Ép bả vai ra sau và xuống, ưỡn nhẹ ngực, chân bám sàn.', 'Nắm rộng hơn vai khoảng 1,5 lần.'],
    steps: ['Gỡ tạ, đưa thanh lên trên ngực giữa.', 'Hạ có kiểm soát chạm ngực dưới (ngang núm vú).', 'Đẩy lên và hơi lùi về phía mặt.'],
    cues: ['Khuỷu 45–70° so với thân.', 'Mông luôn chạm ghế.'],
    mistakes: ['Nảy tạ khỏi ngực.', 'Bả vai nhô lên ở đầu rep.'],
    safety: 'Tạ nặng cần người trợ lực hoặc tập trong khung có chốt an toàn.',
    video: 'barbell bench press form',
  }),
  'Flat Dumbbell Press': G({
    muscles: 'Ngực, vai trước, tay sau',
    rx: '3 × 8–12 · nghỉ 90s',
    setup: ['Ghế phẳng, dùng gối đẩy tạ lên vị trí ngực.', 'Bả vai ép ra sau, chân bám sàn.'],
    steps: ['Đẩy tạ lên trên ngực.', 'Hạ chậm đến khi ngực căng, khuỷu khoảng 45°.', 'Đẩy lên.'],
    cues: ['Biên độ sâu, kiểm soát.'],
    mistakes: ['Hạ nông.', 'Khuỷu bè 90°.'],
    safety: '',
    video: 'flat dumbbell bench press form',
  }),
  'Push-up': G({
    muscles: 'Ngực, vai trước, tay sau, cơ lõi',
    rx: '3 × tối đa (8–15) · nghỉ 60s',
    setup: ['Tay rộng hơn vai một chút, thân thẳng từ đầu đến gót.', 'Chưa đủ sức: chống gối hoặc chống tay lên ghế.'],
    steps: ['Hạ ngực gần chạm sàn, khuỷu khoảng 45°.', 'Đẩy lên đến thẳng tay.'],
    cues: ['Siết mông và bụng, không võng hông.'],
    mistakes: ['Hông chảy xuống.', 'Chỉ cúi đầu, ngực không xuống.'],
    safety: 'Để trống ô kg = bodyweight.',
    video: 'push up proper form',
  }),
  'Overhead Barbell Press': G({
    muscles: 'Vai trước, vai giữa, tay sau',
    rx: '3 × 6–8 · nghỉ 120s',
    setup: ['Đứng, thanh ở ngực trên, nắm rộng hơn vai một chút.', 'Siết mông và bụng.'],
    steps: ['Đẩy thanh thẳng lên, đưa đầu ra sau nhẹ cho thanh đi qua.', 'Khoá tay trên đầu, đầu đưa trở lại dưới thanh.', 'Hạ có kiểm soát về ngực trên.'],
    cues: ['Thanh đi thẳng đứng.', 'Không ưỡn lưng thành đẩy ngực dốc.'],
    mistakes: ['Ưỡn lưng dưới.', 'Dùng gối bật tạ.'],
    safety: '',
    video: 'overhead press barbell form',
  }),
  'Seated Cable Row': G({
    muscles: 'Lưng giữa, xô, vai sau',
    rx: '3 × 10–12 · nghỉ 75s',
    setup: ['Ngồi, chân đạp tấm chắn, gối hơi chùng.', 'Thân thẳng, cầm tay cầm chữ V.'],
    steps: ['Kéo tay cầm về bụng, ép bả vai.', 'Thả ra chậm, để bả vai trượt ra trước.'],
    cues: ['Thân gần như đứng yên.', 'Khuỷu sát thân.'],
    mistakes: ['Ngả người ra sau kéo.'],
    safety: '',
    video: 'seated cable row form',
  }),
  'Assisted Pull-up': G({
    muscles: 'Xô, lưng giữa, tay trước',
    rx: '3 × 8–10 · nghỉ 90s',
    setup: ['Máy hỗ trợ: chọn mức đỡ để làm được 8–10 rep sạch. Hoặc móc dây kháng lực dưới gối.'],
    steps: ['Treo thẳng tay, hạ vai.', 'Kéo khuỷu xuống đến khi cằm qua xà.', 'Hạ chậm hết biên độ.'],
    cues: ['Giảm dần mức hỗ trợ theo tuần.'],
    mistakes: ['Nửa biên độ.'],
    safety: 'Ô kg: nhập mức hỗ trợ (vd. 20 = đỡ 20 kg). Số càng nhỏ càng khoẻ.',
    video: 'assisted pull up machine form',
  }),
  'Conventional Deadlift': G({
    muscles: 'Toàn bộ chuỗi sau: đùi sau, mông, lưng',
    rx: '3 × 5–6 · nghỉ 150s',
    setup: ['Thanh trên giữa bàn chân, chân rộng bằng hông.', 'Cúi nắm thanh ngay ngoài chân, hạ hông đến khi ống quyển chạm thanh.', 'Lưng thẳng, ngực ưỡn, kéo căng thanh trước khi nhấc.'],
    steps: ['Đạp sàn, đẩy hông ra trước, thanh trượt sát chân lên.', 'Đứng thẳng, siết mông, không ngả ra sau.', 'Hạ ngược lại: đẩy hông ra sau trước, qua gối mới co gối.'],
    cues: ['"Đẩy sàn ra xa", không giật thanh.'],
    mistakes: ['Cong lưng.', 'Thanh rời xa chân.'],
    safety: 'Bắt đầu nhẹ để luyện kỹ thuật; đau lưng thì dừng.',
    video: 'conventional deadlift form',
  }),
  'Leg Press': G({
    muscles: 'Đùi trước, mông',
    rx: '3 × 10–12 · nghỉ 90s',
    setup: ['Lưng và hông áp sát đệm.', 'Chân rộng bằng vai giữa tấm đạp (đặt cao hơn để vào mông nhiều hơn).'],
    steps: ['Mở chốt, hạ tấm đạp đến khi gối gần 90° hoặc sâu hơn nếu hông không cuộn.', 'Đạp lên, không khoá cứng gối.'],
    cues: ['Đạp bằng gót và giữa bàn chân.'],
    mistakes: ['Hạ quá sâu làm mông nhấc khỏi đệm.', 'Khoá thẳng gối ở trên.'],
    safety: '',
    video: 'leg press form',
  }),
  'Leg Extension': G({
    muscles: 'Đùi trước (cô lập)',
    rx: '3 × 12–15 · nghỉ 60s',
    setup: ['Khớp gối thẳng hàng trục xoay, đệm tì trên cổ chân.'],
    steps: ['Duỗi gối đến thẳng, siết đùi 1 giây.', 'Hạ chậm.'],
    cues: ['Giữ chặt tay cầm, hông không nhấc.'],
    mistakes: ['Đá tạ lấy đà.'],
    safety: '',
    video: 'leg extension form',
  }),
  'Walking Lunge': G({
    muscles: 'Mông, đùi trước',
    rx: '3 × 10–12 mỗi chân · nghỉ 90s',
    setup: ['Cầm tạ đơn hai tay, đứng thẳng.'],
    steps: ['Bước dài ra trước, hạ đến khi gối sau gần chạm sàn.', 'Đạp chân trước, bước chân sau lên thành bước tiếp theo.'],
    cues: ['Thân thẳng hoặc hơi nghiêng ra trước.', 'Gối trước theo mũi chân.'],
    mistakes: ['Bước quá ngắn làm gối đẩy xa ra trước.'],
    safety: '',
    video: 'dumbbell walking lunge form',
  }),
  'Standing Calf Raise': G({
    muscles: 'Bắp chân',
    rx: '3 × 12–15 · nghỉ 60s',
    setup: ['Mũi bàn chân trên bục, gót buông tự do.'],
    steps: ['Hạ gót xuống hết căng.', 'Kiễng lên cao nhất, giữ 1 giây.'],
    cues: ['Biên độ đầy đủ, nhịp chậm.'],
    mistakes: ['Nảy nhanh nửa biên độ.'],
    safety: '',
    video: 'standing calf raise form',
  }),
  'Hammer Curl': G({
    muscles: 'Tay trước, cơ cánh tay, cẳng tay',
    rx: '3 × 10–12 · nghỉ 60s',
    setup: ['Cầm tạ đơn, lòng bàn tay hướng vào nhau.'],
    steps: ['Cuộn tạ lên giữ nguyên hướng cầm.', 'Hạ chậm.'],
    cues: ['Khuỷu sát thân.'],
    mistakes: ['Đung đưa thân.'],
    safety: '',
    video: 'hammer curl form',
  }),
  'Cable Crunch': G({
    muscles: 'Cơ bụng thẳng',
    rx: '3 × 12–15 · nghỉ 60s',
    setup: ['Quỳ trước ròng rọc cao, cầm dây thừng hai bên đầu.'],
    steps: ['Cuộn thân xuống, đưa khuỷu về phía đùi.', 'Siết bụng, rồi trở về chậm.'],
    cues: ['Hông cố định; chuyển động ở cột sống.'],
    mistakes: ['Ngồi xuống bằng hông thay vì cuộn bụng.'],
    safety: '',
    video: 'cable crunch form',
  }),
  'Hip Thrust (Barbell)': G({
    muscles: 'Mông (chính), đùi sau',
    rx: '4 × 8–12 · nghỉ 90s',
    setup: ['Lưng trên tựa mép ghế (ngang bả vai), thanh đặt trên nếp hông, lót đệm.', 'Chân rộng bằng hông, gối gập khoảng 90° ở điểm cao nhất.'],
    steps: ['Cằm hơi cúi, đẩy hông lên đến khi thân song song sàn.', 'Siết mông 1–2 giây ở đỉnh.', 'Hạ có kiểm soát.'],
    cues: ['Xương chậu cuộn nhẹ (posterior tilt) ở đỉnh, không ưỡn lưng.', 'Đạp bằng gót.'],
    mistakes: ['Ưỡn lưng dưới thay vì dùng mông.', 'Chân quá xa (đùi sau làm việc nhiều).'],
    safety: 'Dùng đệm lót thanh để không đau xương hông.',
    video: 'barbell hip thrust form',
  }),
  'Glute Bridge': G({
    muscles: 'Mông',
    rx: '3 × 12–15 · nghỉ 60s',
    setup: ['Nằm ngửa trên sàn, gối co, bàn chân gần mông. Có thể đặt tạ đơn/thanh trên hông.'],
    steps: ['Đẩy hông lên, siết mông 2 giây.', 'Hạ chậm, không thả hẳn xuống sàn giữa các rep.'],
    cues: ['Cuộn xương chậu, sườn hạ xuống.'],
    mistakes: ['Ưỡn lưng.'],
    safety: 'Để trống ô kg nếu tập không tạ.',
    video: 'glute bridge form',
  }),
  'Goblet Squat': G({
    muscles: 'Đùi trước, mông, cơ lõi',
    rx: '3–4 × 10–12 · nghỉ 90s',
    setup: ['Ôm một tạ đơn/tạ ấm sát ngực, khuỷu hướng xuống.', 'Chân rộng hơn vai một chút.'],
    steps: ['Ngồi thẳng xuống giữa hai gót, khuỷu đi vào giữa gối.', 'Đứng lên đạp cả bàn chân.'],
    cues: ['Thân thẳng đứng, ngực mở.'],
    mistakes: ['Gót nhấc khỏi sàn.'],
    safety: '',
    video: 'goblet squat form',
  }),
  'Cable Glute Kickback': G({
    muscles: 'Mông',
    rx: '3 × 12–15 mỗi chân · nghỉ 45s',
    setup: ['Ròng rọc thấp, đeo đai cổ chân, tay vịn máy, nghiêng thân ra trước.'],
    steps: ['Đá chân ra sau–lên, siết mông ở cuối.', 'Đưa về chậm.'],
    cues: ['Không ưỡn lưng; chuyển động ở hông.'],
    mistakes: ['Vung chân bằng đà.'],
    safety: '',
    video: 'cable glute kickback form',
  }),
  'Hip Abduction Machine': G({
    muscles: 'Mông nhỡ, mông bé (hông ngoài)',
    rx: '3 × 15–20 · nghỉ 45s',
    setup: ['Ngồi máy, đệm tì mặt ngoài đùi. Nghiêng thân ra trước nhẹ để vào mông nhiều hơn.'],
    steps: ['Mở đùi ra ngoài, giữ 1 giây.', 'Khép về chậm, không để tạ chạm.'],
    cues: ['Biên độ đầy đủ, nhịp chậm.'],
    mistakes: ['Dùng quán tính bật ra.'],
    safety: '',
    video: 'hip abduction machine glute form',
  }),
  'Back Extension (Glute focus)': G({
    muscles: 'Mông, đùi sau, lưng dưới',
    rx: '3 × 12–15 · nghỉ 60s',
    setup: ['Ghế 45°, mép đệm ngay dưới xương hông, mũi chân xoay ra ngoài.', 'Lưng trên hơi tròn.'],
    steps: ['Gập hông hạ thân xuống.', 'Đẩy hông vào đệm, siết mông để đưa thân lên ngang chân.'],
    cues: ['Không ưỡn quá cao ở trên.'],
    mistakes: ['Dùng lưng dưới kéo lên.'],
    safety: 'Có thể ôm đĩa tạ khi đã nhẹ.',
    video: 'glute focused back extension 45 degree',
  }),
  'Step-up': G({
    muscles: 'Mông, đùi trước (từng chân)',
    rx: '3 × 10 mỗi chân · nghỉ 60s',
    setup: ['Bục/ghế cao ngang gối, cầm tạ đơn hai tay.'],
    steps: ['Đặt cả bàn chân lên bục, đạp gót để đứng lên.', 'Hạ chậm bằng chân trên bục.'],
    cues: ['Không bật bằng chân dưới.'],
    mistakes: ['Bục quá cao làm lưng gập.'],
    safety: '',
    video: 'dumbbell step up glute form',
  }),
  'Dead Bug': G({
    muscles: 'Cơ lõi sâu, bụng',
    rx: '3 × 8–10 mỗi bên · nghỉ 45s',
    setup: ['Nằm ngửa, tay thẳng lên trần, hông và gối 90°.', 'Ép lưng dưới sát sàn.'],
    steps: ['Duỗi tay phải và chân trái ra xa cùng lúc, thở ra.', 'Về vị trí đầu, đổi bên.'],
    cues: ['Lưng dưới không rời sàn.'],
    mistakes: ['Làm nhanh, ưỡn lưng.'],
    safety: 'Để trống ô kg; ô rep nhập số lần mỗi bên.',
    video: 'dead bug exercise form',
  }),
  Plank: G({
    muscles: 'Cơ lõi',
    rx: '3 × 30–60 giây · nghỉ 45s',
    setup: ['Chống khuỷu dưới vai, thân thẳng từ đầu đến gót.'],
    steps: ['Siết bụng và mông, giữ tư thế.', 'Thở đều.'],
    cues: ['Hông ngang vai, không võng hay chổng mông.'],
    mistakes: ['Giữ quá lâu khi tư thế đã sụp.'],
    safety: 'Ô thời gian: nhập số giây giữ được.',
    video: 'plank proper form',
  }),
  'Incline Treadmill Walk (Zone 2)': G({
    muscles: 'Tim mạch, đốt năng lượng',
    rx: '20–40 phút · nhịp tim vùng 2',
    setup: ['Máy chạy dốc 6–12%, tốc độ 4,5–5,5 km/h.'],
    steps: ['Đi bộ đều, không vịn tay vào máy.', 'Giữ cường độ nói chuyện được thành câu (vùng 2, ~60–70% nhịp tim tối đa).'],
    cues: ['Đều đặn quan trọng hơn cường độ cao.'],
    mistakes: ['Bám tay vịn làm giảm hiệu quả.'],
    safety: 'Ô thời gian: nhập số phút đã đi.',
    video: 'incline treadmill walk zone 2',
  }),
  'Mobility & Stretching': G({
    muscles: 'Hông, vai, cột sống ngực',
    rx: '10–15 phút',
    setup: ['Thảm tập, không cần tạ.'],
    steps: ['Giãn gập hông (half-kneeling) 2 × 30 giây/bên.', 'Giãn ngực ở khung cửa 2 × 30 giây.', 'Mở cột sống ngực (thoracic rotation) 2 × 8/bên.', 'Tư thế em bé, giãn xô 2 × 30 giây.', 'Giãn đùi sau, mông (pigeon) 2 × 30 giây/bên.'],
    cues: ['Thở chậm, không ép đau.'],
    mistakes: [],
    safety: 'Ô thời gian: nhập số phút.',
    video: 'full body mobility routine 10 minutes',
  }),
};

export const guideFor = (name) => GUIDES[name] || null;
export const videoUrl = (g) => `https://www.youtube.com/results?search_query=${encodeURIComponent(g.video)}`;
